using ArcadiaParties.Data.Abstractions.Repositories;
using System.Threading.Tasks;

namespace ArcadiaParties.Data.Repositories
{
    public class AssistantTokenRepository : IAssistantTokenRepository
    {
        public async Task<string> GetToken()
        {
            var bearer = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJhMmNjYjIyMS02MGUyLTQ3YjgtYjI4Yy1iZjg4YTU5ZjdmNGEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMvIiwiaWF0IjoxNTg1MDQ5Mjg4LCJuYmYiOjE1ODUwNDkyODgsImV4cCI6MTU4NTA1MzE4OCwiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhPQUFBQVZVM2lqb2FLNlZhV2I3M0s0OUo3M3RZUWVxNnJyZG5aY2hyUWhuT2JiNHMrcGMvVU0xbnkwZ3A0RWVFeTdUZFZ5Nk9SZlNFbDlEYkRNcXdkNmRnOXdnPT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiYTJjY2IyMjEtNjBlMi00N2I4LWIyOGMtYmY4OGE1OWY3ZjRhIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJLdXpuZXRzb3ZhIiwiZ2l2ZW5fbmFtZSI6IkVrYXRlcmluYSIsImlwYWRkciI6IjE4NS4xMzQuNzQuNSIsIm5hbWUiOiJLdXpuZXRzb3ZhLCBFa2F0ZXJpbmEiLCJvaWQiOiI5NjgwMGQyMC02MDNiLTRhZTUtOGM5MS03YzdlN2Q3YWE5OGEiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzE3Mjc1NTkzLTExMzkwOTk3ODQtMTUwMTE4NzkxMS0xODcwNCIsInNjcCI6IlVzZXIuUmVhZCIsInN1YiI6IjAzMHVpUFdyTHpDRmlOdTFrcmpwNjJfOG5MS0o0UFdDVkkyT2pWdVJTLVkiLCJ0aWQiOiJmYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMiLCJ1bmlxdWVfbmFtZSI6ImVrYXRlcmluYS5rdXpuZXRzb3ZhQGFyY2FkaWEuc3BiLnJ1IiwidXBuIjoiZWthdGVyaW5hLmt1em5ldHNvdmFAYXJjYWRpYS5zcGIucnUiLCJ1dGkiOiJOcmhXV3VZeU8wU1lySWtfem0xQ0FBIiwidmVyIjoiMS4wIn0.A1PnvIhgzc8Vo2svcIOZMAL3g0JYogX1YBkTvygMAnUzOeCzd94YpZT2criL_EeuIqghszDL8h9io2mxKhGvb1IIXUeVidqWWJma_vfcXTsjuOocyxEttUZuEK0LWIck-hC6F3EPzFSWrjlt5khsovRQDCLNYV_vYQYGpKQrtlggGn5FnEcj0cY329y8fEOtH6gGtPKGEUNHMRIfGy2Ic6z--9CP0F8lED_7IZwwk5vrpmCrVdsfbBcS3d9idQKDu3nkVUf5m-Ws1uxKlYsLEGzdDY0ztTpJ9K16XL5F-nqVcgYN_yc-pwyeAcgEq7XPiDpGlm5XtmFjMtpdUK8uCw";
            return bearer;
        }
    }
}
