using ArcadiaParties.Data.Abstractions.Repositories;
using System.Threading.Tasks;

namespace ArcadiaParties.Data.Repositories
{
    public class AssistantTokenRepository : IAssistantTokenRepository
    {
        public async Task<string> GetToken()
        {
            var bearer = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJhMmNjYjIyMS02MGUyLTQ3YjgtYjI4Yy1iZjg4YTU5ZjdmNGEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMvIiwiaWF0IjoxNTg1MzEyNzExLCJuYmYiOjE1ODUzMTI3MTEsImV4cCI6MTU4NTMxNjYxMSwiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhQQUFBQUhIKzBMdEIxVzIwQ2pqR1dNdFl5Lzk2STYza3ZEenMvVWlIeWdxVWdiVlIzNlVNRENrVFI5dFVBZk9lUFQ5b1pGZWRjOWhrUi9WYVdyVTFIelNDYVJBPT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiYTJjY2IyMjEtNjBlMi00N2I4LWIyOGMtYmY4OGE1OWY3ZjRhIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJLdXpuZXRzb3ZhIiwiZ2l2ZW5fbmFtZSI6IkVrYXRlcmluYSIsImlwYWRkciI6IjE4NS4xMzQuNzQuNSIsIm5hbWUiOiJLdXpuZXRzb3ZhLCBFa2F0ZXJpbmEiLCJvaWQiOiI5NjgwMGQyMC02MDNiLTRhZTUtOGM5MS03YzdlN2Q3YWE5OGEiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzE3Mjc1NTkzLTExMzkwOTk3ODQtMTUwMTE4NzkxMS0xODcwNCIsInNjcCI6IlVzZXIuUmVhZCIsInN1YiI6IjAzMHVpUFdyTHpDRmlOdTFrcmpwNjJfOG5MS0o0UFdDVkkyT2pWdVJTLVkiLCJ0aWQiOiJmYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMiLCJ1bmlxdWVfbmFtZSI6ImVrYXRlcmluYS5rdXpuZXRzb3ZhQGFyY2FkaWEuc3BiLnJ1IiwidXBuIjoiZWthdGVyaW5hLmt1em5ldHNvdmFAYXJjYWRpYS5zcGIucnUiLCJ1dGkiOiJqbkJUN3FYYWNrMlEzRW56ZDRVUUFBIiwidmVyIjoiMS4wIn0.bcfmAGpY6K91BegiUkVEvtQXlhJpdVUziBuPkAMrNFAQaw0dlfUwgVo5NyjXNPxKlGSsjtlpwIxkt8uytovJ3VXYWnMxzNUQx8ogv9Cw-2rtfmmR8w4gYWjl-1KB3NteVN-RjFnnhJEZDVVHgopWl9rZ2-Gj4ojknOrJImvT7tqhG0b8iyyE-Rln5HwXeYElaB6785jI-SHdrEYB2iK-PdRA9ICwe6bfb0QMs65E7UxQzT9lvTDBX7KnUJ2Q6XHP91gexssTVu7vMAbypZZ4noW0RmIe9rlvagvaMgeeqam_3XfQHAFUsurN-y7TLb0DGjXw9hjte-lvJv2s7VX87w";
            return bearer;
        }
    }
}
