using ArcadiaParties.Data.Abstractions.Repositories;
using System.Threading.Tasks;

namespace ArcadiaParties.Data.Repositories
{
    public class AssistantTokenRepository : IAssistantTokenRepository
    {
        public async Task<string> GetToken()
        {
            var bearer = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJhMmNjYjIyMS02MGUyLTQ3YjgtYjI4Yy1iZjg4YTU5ZjdmNGEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMvIiwiaWF0IjoxNTg1MjI5MTk5LCJuYmYiOjE1ODUyMjkxOTksImV4cCI6MTU4NTIzMzA5OSwiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhQQUFBQXhwenhjV2I2NHlhNUswTk96RUhndkp6Vm8wMytDeHFjaUMwZW8waWFTRDd6Sk1CVEZxeUwvVUUrQmlOeGNyVG03MENUc1BKZGpaYlBFTis4MHRVYXhnPT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiYTJjY2IyMjEtNjBlMi00N2I4LWIyOGMtYmY4OGE1OWY3ZjRhIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJLdXpuZXRzb3ZhIiwiZ2l2ZW5fbmFtZSI6IkVrYXRlcmluYSIsImlwYWRkciI6IjE4NS4xMzQuNzQuNSIsIm5hbWUiOiJLdXpuZXRzb3ZhLCBFa2F0ZXJpbmEiLCJvaWQiOiI5NjgwMGQyMC02MDNiLTRhZTUtOGM5MS03YzdlN2Q3YWE5OGEiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzE3Mjc1NTkzLTExMzkwOTk3ODQtMTUwMTE4NzkxMS0xODcwNCIsInNjcCI6IlVzZXIuUmVhZCIsInN1YiI6IjAzMHVpUFdyTHpDRmlOdTFrcmpwNjJfOG5MS0o0UFdDVkkyT2pWdVJTLVkiLCJ0aWQiOiJmYTRlOWMxZi02MjIyLTQ0M2QtYTA4My0yOGY4MGMxZmZlZmMiLCJ1bmlxdWVfbmFtZSI6ImVrYXRlcmluYS5rdXpuZXRzb3ZhQGFyY2FkaWEuc3BiLnJ1IiwidXBuIjoiZWthdGVyaW5hLmt1em5ldHNvdmFAYXJjYWRpYS5zcGIucnUiLCJ1dGkiOiI4SVhBVzJUUU5FT2dUc1NhYkFNV0FBIiwidmVyIjoiMS4wIn0.cLnMy3yCncWnSUDwxg-UhRnDOeVbo672JjEse2vOiKpfHe1PigPomryr1xyRKT6nQb_Zq9V_n_BqjsMRbQLlGdtjvgI_JLspsrbzgSImf8f6ksuM4aToLR7uMfD4FPEHXcWz4o_ESjJFoXnk_Sk-gjKAQK8ip7QNKJ9WzBWnqtWOnnxLPKhnfmQAZhF66oKybRqW42UcPXrEDtalCfpO8L7cGgX4Vh1sXdpDotBexwBm6WEqJSux4rQ6kPh854aMLlStLf7RKjzDmBIGoPt7-etxJUhm5iFccWRf3Rv0Wr1agFYTu_15QUrO5bvbQ2HxDUWZeMAH9aIzkCcE7P0hpw";
            return bearer;
        }
    }
}
